# Generated by Django 2.1.1 on 2018-10-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlayerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerimage',
            name='cover_img_ind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='playerimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_image_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerimage',
            name='profile_img_ind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='playerimage',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='playerimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_image_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerimage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_video_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playervideo',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_video_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
