# Generated by Django 2.1.1 on 2018-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerApp', '0002_auto_20181021_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerimage',
            name='cover_img_ind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerimage',
            name='profile_img_ind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerimage',
            name='public_ind',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='public_ind',
            field=models.BooleanField(default=True),
        ),
    ]
