# Generated by Django 2.1.1 on 2018-09-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0030_remove_profile_country'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
