# Generated by Django 2.1.1 on 2018-09-27 08:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_auto_20180925_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
