# Generated by Django 2.1.1 on 2018-09-27 08:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0012_auto_20180927_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='icon',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/media/'), upload_to='country'),
        ),
    ]
