# Generated by Django 2.1.1 on 2018-09-27 09:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0013_auto_20180927_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='icon',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='/media/'), upload_to='country'),
        ),
    ]
