# Generated by Django 2.1.1 on 2018-09-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamimages', to='TeamApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='team/videos/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamvideos', to='TeamApp.Team')),
            ],
        ),
    ]
