# Generated by Django 2.1.1 on 2018-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0003_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='status',
            field=models.NullBooleanField(default=None),
        ),
    ]
