# Generated by Django 2.1.1 on 2018-09-30 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamApp', '0004_teaminvite_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together={('from_user', 'to_user', 'team')},
        ),
    ]
