# Generated by Django 2.1.1 on 2018-09-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0005_auto_20180930_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together=set(),
        ),
    ]
