# Generated by Django 2.1.1 on 2018-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0007_auto_20181003_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
