# Generated by Django 2.1.1 on 2018-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0008_teaminvite_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('K', 'Kicked'), ('L', 'Left'), ('C', 'Cancel')], max_length=1, null=True),
        ),
    ]
