# Generated by Django 2.1.1 on 2018-10-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0012_sport_sporticon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='description1',
            new_name='description',
        ),
    ]
