# Generated by Django 2.1.1 on 2018-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0013_auto_20181016_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='teamimage',
            name='cover_img_ind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teamimage',
            name='profile_img_ind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teamimage',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='teamvideo',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
