# Generated by Django 2.1.1 on 2018-10-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamApp', '0015_auto_20181021_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sporticon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sporticon',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='sporticon',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='SportIcon',
        ),
    ]
