# Generated by Django 2.1.1 on 2018-10-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0018_sport_sporticon'),
        ('TeamApp', '0017_teampreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampreference',
            name='sport',
        ),
        migrations.AddField(
            model_name='teampreference',
            name='sport',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='lookup.Sport'),
            preserve_default=False,
        ),
    ]
