# Generated by Django 2.1.1 on 2018-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0002_auto_20180919_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('DOB', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('facebook_id', models.TextField()),
                ('google_id', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
