# Generated by Django 2.1.1 on 2018-09-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0005_remove_userextension_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='longitude',
            field=models.FloatField(max_length=12),
        ),
    ]
