# Generated by Django 2.1.1 on 2018-09-21 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRegistrationApp', '0007_auto_20180920_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='id',
        ),
        migrations.AddField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
