# Generated by Django 2.1.1 on 2018-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0009_auto_20180921_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='uid',
            new_name='id',
        ),
    ]
