# Generated by Django 2.1.1 on 2018-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0010_auto_20180921_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
