# Generated by Django 2.1.1 on 2018-09-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0011_auto_20180921_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='user',
        ),
    ]
