# Generated by Django 2.1.1 on 2018-09-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0012_remove_userextension_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='weight',
        ),
        migrations.AddField(
            model_name='userextension',
            name='hellow',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
