# Generated by Django 2.1.1 on 2018-09-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0013_auto_20180921_0812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtension',
        ),
    ]
