# Generated by Django 2.1.1 on 2018-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserRegistrationApp', '0014_delete_userextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('DOB', models.DateField(null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('facebook_id', models.TextField()),
                ('google_id', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
