# Generated by Django 2.1.1 on 2018-09-21 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRegistrationApp', '0017_userextension_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtension',
            new_name='Profile',
        ),
    ]
