# Generated by Django 2.1.1 on 2018-09-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0018_auto_20180921_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
