# Generated by Django 2.1.1 on 2018-09-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0019_auto_20180921_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
