# Generated by Django 2.1.1 on 2018-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0028_auto_20180924_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
