# Generated by Django 2.1.1 on 2018-09-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_country'),
        ('UserRegistrationApp', '0030_remove_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.Country'),
            preserve_default=False,
        ),
    ]
