# Generated by Django 2.1.1 on 2018-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0031_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
