# Generated by Django 2.1.1 on 2018-09-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_auto_20180924_1126'),
        ('UserRegistrationApp', '0033_remove_profile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.City'),
            preserve_default=False,
        ),
    ]
