# Generated by Django 2.1.1 on 2018-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0038_auto_20180925_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_profile_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_profile_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
