# Generated by Django 2.1.1 on 2018-10-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0018_sport_sporticon'),
        ('UserRegistrationApp', '0040_profile_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.Country')),
                ('sport', models.ManyToManyField(blank=True, null=True, to='lookup.Sport')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='profile',
            name='follow_profile_ind',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_profile_ind',
            field=models.BooleanField(default=True),
        ),
    ]
