# Generated by Django 2.1.1 on 2018-10-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRegistrationApp', '0041_auto_20181022_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preference_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
