# Generated by Django 2.1.1 on 2018-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0043_auto_20181022_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='sport',
            field=models.ManyToManyField(blank=True, to='lookup.Sport'),
        ),
    ]
