# Generated by Django 2.1.1 on 2018-10-23 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRegistrationApp', '0044_auto_20181023_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preference_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preference',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preference_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preference',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
