# Generated by Django 2.1.1 on 2018-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0045_auto_20181023_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Player'), ('T', 'Trainer'), ('B', 'Both')], max_length=1, null=True),
        ),
    ]
