# Generated by Django 2.1.1 on 2018-10-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRegistrationApp', '0047_auto_20181024_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='request_type',
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
