# Generated by Django 2.1.1 on 2018-10-24 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0018_sport_sporticon'),
        ('UserRegistrationApp', '0051_auto_20181024_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preference',
            new_name='UserPreference',
        ),
    ]
