# Generated by Django 2.1.1 on 2018-10-24 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationApp', '0052_auto_20181024_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_preference_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_preference_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
