# Generated by Django 2.1.1 on 2018-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0002_activity_activityimage_activityinvite_activityrating_activityvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
