# Generated by Django 2.1.1 on 2018-10-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0003_activity_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activityrating',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
