# Generated by Django 2.1.1 on 2018-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0005_auto_20181014_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
