# Generated by Django 2.1.1 on 2018-10-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ActivityApp', '0007_activity_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_image_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityimage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_invite_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityinvite',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityinvite',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityinvite',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityrating',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityrating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_video_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_image_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityrating',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityvideo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_video_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
