# Generated by Django 2.1.1 on 2018-10-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0008_auto_20181014_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activityinvite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activityrating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activityvideo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
