# Generated by Django 2.1.1 on 2018-10-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0009_auto_20181014_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rating_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
