# Generated by Django 2.1.1 on 2018-10-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0010_auto_20181016_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='activityimage',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
