# Generated by Django 2.1.1 on 2018-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0011_auto_20181021_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='public_ind',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='public_ind',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activityvideo',
            name='public_ind',
            field=models.BooleanField(default=True),
        ),
    ]
