# Generated by Django 2.1.1 on 2018-10-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0013_activitypreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitypreference',
            old_name='team',
            new_name='activity',
        ),
    ]
