# Generated by Django 2.1.1 on 2018-11-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VenueApp', '0008_auto_20181101_2124'),
        ('ActivityApp', '0014_auto_20181031_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='VenueApp.Venue'),
        ),
    ]
