# Generated by Django 2.1.1 on 2018-10-14 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VenueApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venueadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='days_open_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='days_open_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='hours_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='hours_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
