# Generated by Django 2.1.1 on 2018-10-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenueApp', '0002_auto_20181014_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='days_open_from',
            field=models.CharField(blank=True, choices=[('sun', 'Sunday'), ('mon', 'monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='days_open_to',
            field=models.CharField(blank=True, choices=[('sun', 'Sunday'), ('mon', 'monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=1, null=True),
        ),
    ]
