# Generated by Django 2.1.1 on 2018-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenueApp', '0004_auto_20181015_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueimage',
            name='cover_img_ind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='profile_img_ind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='venuerating',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='venuevideo',
            name='public_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
