# Generated by Django 2.1.1 on 2018-11-01 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0018_sport_sporticon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VenueApp', '0007_activitypreference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPreference',
            new_name='VenuePreference',
        ),
    ]
